db = db.getSiblingDB('notes')
db.user.createIndex( { Name: 1 }, { unique: true } )
db.notes.createIndex( { Title: "text", Content: "text", Notebook: "text", Tags: "text" } )
db.notes.createIndex( { owner: 1, trash: 1 } )
db.notes.createIndex( { _id: 1, owner: 1, trash: 1 } )
db.notes.createIndex( { owner: 1, trash: 1, notebook: 1 } )
db.notes.createIndex( { _id: 1, owner: 1, trash: 1, notebook: 1 })
db.notes.createIndex( { owner: 1, trash: 1, tags: 1 } )
db.notes.createIndex( { _id: 1, owner: 1, trash: 1, tags: 1 })
