db = db.getSiblingDB('notes')
db.user.createIndex( { username: 1 }, { unique: true } )
db.notes.createIndex( { title: "text", content: "text", notebook: "text", tags: "text" } )
db.notes.createIndex( { owner: 1, trash: 1 } )
db.notes.createIndex( { _id: 1, owner: 1, trash: 1 } )
db.notes.createIndex( { owner: 1, trash: 1, notebook: 1 } )
db.notes.createIndex( { _id: 1, owner: 1, trash: 1, notebook: 1 } )
db.notes.createIndex( { owner: 1, trash: 1, tags: 1 } )
db.notes.createIndex( { _id: 1, owner: 1, trash: 1, tags: 1 } )
db.token.createIndex( { created: 1 }, { expireAfterSeconds: 3600 } )
